# Changes here will be overwritten by Copier
Authors: Martin Köhler, Christian Kirches
JuliaMinVersion: '1.12'
License: MIT
LicenseCopyrightHolders: Martin Köhler, Christian Kirches
PackageName: CutNorm
PackageOwner: koehler-martin
PackageUUID: 96b8343c-58ad-55ba-b7ce-8a87c9ec6d10
StrategyConfirmIncluded: false
StrategyLevel: 1
StrategyReviewExcluded: true
_src_path: C:\.julia\packages\BestieTemplate\MPEqY
